"$schema" = "https://starship.rs/config-schema.json"

command_timeout = 1500

format = """
[](fg:color_blue)\
$os\
$username\
$hostname\
[ ](fg:color_blue bg:color_blue)\
$directory\
[ ](fg:color_blue bg:color_bg3)\
$git_branch\
[ ](fg:color_bg3 bg:color_bg3)\
$git_status\
[ ](fg:color_bg3 bg:color_bg4)\
$c\
$dotnet\
$java\
$kotlin\
$nodejs\
[ ](fg:color_bg4 bg:color_bg5)\
$cmd_duration\
[ ](fg:color_bg5)\
\n$character\
"""

palette = "ccswe_dark"

[palettes.ccswe_dark]
color_bg1 = "#e6e9ef"
color_bg2 = "#c6d0f5"
color_bg3 = "#acb0be"
color_bg4 = "#bcc0cc"
color_bg5 = "#ccd0da"

color_blue = "#2f5783"
color_gray = "#6c6f85"
color_black = "#000"
color_red = "#e64553"
color_gray2 = "#5c5f77"
color_white = "#e6e9ef"

[character]
error_symbol = "[❯](bold color_red)"
success_symbol = "[❯](bold color_blue)"

[cmd_duration]
format = "[$duration](bg:color_bg5 fg:color_gray)"
min_time = 500

[directory]
style = "bg:color_blue fg:color_white"
format = "[$path]($style)"
truncation_length = 3
truncation_symbol = "../"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:color_bg3 fg:color_blue"
format = "[$symbol $branch]($style)"

[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
deleted = ""
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
format = '[( $all_status$ahead_behind)]($style)'
style = "bold bg:color_bg3 fg:color_red"

[hostname]
format = "[@$hostname]($style)"
ssh_only = true
ssh_symbol = " "
style = "bg:color_bg1 fg:color_gray2"

[os]
format = "[$symbol]($style)"
style = "bg:color_blue fg:color_white"
disabled = false

[username]
disabled = false
format = "[$user]($style)"
show_always = false
style_root = "bg:color_bg1 fg:color_red"
style_user = "bg:color_bg1 fg:color_gray2"

# Code symbols
[c]
format = '[$symbol]($style)'
style = "bg:color_bg4 fg:#6295CB"
symbol = " "

[dotnet]
format = '[$symbol]($style)'
style = "bg:color_bg4 fg:#1180C3"
symbol = " "

[java]
format = '[$symbol]($style)'
style = "bg:color_bg4 fg:#F7901E"
symbol = " "

[kotlin]
format = '[$symbol]($style)'
style = "bg:color_bg4 fg:#C017E4"
symbol = " "

[nodejs]
style = "bg:color_bg4 fg:#40a02b"
format = '[$symbol($version)]($style)'
symbol = " "

# OS Symbols
[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
